pipeline {
    agent none
    stages{
        stage("Back-end"){
            agent {
                docker {image  "maven:3.8.1-adoptopenjdk-11"}
            }
            steps{
                sh 'mvn --version'
            }
        }
        stage("Front-end"){
            agent{
                docker {image "node:16-alpine"}
            }
            steps{
                sh "node --version"
            }
        }
        stage("DB"){
            agent {
                docker { image "postgres:12.19-bullseye"}
            }
            steps{
                sh "psql --version"
            }
        }
    }
}